const typeData={
 full:{num:'01 / 04',title:'Полные съёмные протезы',text:'Когда зубов на челюсти совсем не осталось. Доступное решение, которое помогает восстановить жевание и внешний вид.',price:'от 40 000 ₽',img:'assets/gallery-02.jpg',facts:['Пластиночный — от 40 000 ₽','С армированием — от 45 000 ₽','Acry Free — от 50 000 ₽'],note:'Acry Free может подойти, если важны меньший вес и эстетика или есть чувствительность к классическому акрилу.'},
 partial:{num:'02 / 04',title:'Частичные съёмные протезы',text:'Когда часть своих зубов сохранена, но нужно закрыть большие промежутки и вернуть нормальную жевательную функцию.',price:'от 35 000 ₽',img:'assets/gallery-04.jpg',facts:['Пластиночный — от 35 000 ₽','Нейлоновый / ацеталовый — от 40 000 ₽','Подбор опорных зубов после осмотра'],note:'Гибкие материалы могут ощущаться комфортнее, но выбор зависит не только от желания — важны прикус и состояние опорных зубов.'},
 temp:{num:'03 / 04',title:'Иммедиат-протез',text:'Временная конструкция на период, пока изготавливается постоянный протез. Помогает не оставаться без зубов после удаления.',price:'от 10 000 ₽',img:'assets/gallery-03.jpg',facts:['Обычно на 1–3 зуба','Временное решение','Срок ношения определяет врач'],note:'Иммедиат-протез не заменяет постоянную конструкцию, но делает переходный период психологически и функционально проще.'},
 clasp:{num:'04 / 04',title:'Бюгельные протезы',text:'Прочная конструкция на тонкой металлической дуге. Подходит, когда есть собственные зубы, которые можно использовать как опору.',price:'по плану лечения',img:'assets/gallery-01.jpg',facts:['Кламмерная фиксация','Замковая фиксация','Меньше закрывает нёбо'],note:'Цена рассчитывается индивидуально: она зависит от фиксации, состояния опорных зубов и необходимости подготовки коронок.'}
};
const tabs=document.querySelectorAll('.type-tab');
const els={num:document.querySelector('#typeNum'),title:document.querySelector('#typeTitle'),text:document.querySelector('#typeText'),price:document.querySelector('#typePrice'),img:document.querySelector('#typeImage'),facts:document.querySelector('#typeFacts'),note:document.querySelector('#typeNote')};
tabs.forEach(tab=>tab.addEventListener('click',()=>{const d=typeData[tab.dataset.type];tabs.forEach(t=>t.classList.remove('active'));tab.classList.add('active');els.img.style.opacity='.2';setTimeout(()=>{els.num.textContent=d.num;els.title.textContent=d.title;els.text.textContent=d.text;els.price.textContent=d.price;els.img.src=d.img;els.facts.innerHTML=d.facts.map(x=>`<span>${x}</span>`).join('');els.note.textContent=d.note;els.img.onload=()=>els.img.style.opacity='1';setTimeout(()=>els.img.style.opacity='1',80)},120)}));
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -50px'});document.querySelectorAll('.reveal:not(.is-visible)').forEach(el=>io.observe(el));
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('.main-nav');toggle?.addEventListener('click',()=>{document.body.classList.toggle('menu-open');nav.classList.toggle('mobile-open')});
